# -*- coding: utf-8 -*-
"""visualize the correlation between features.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DiCjRtliBM-Qge1J8Xiw_Lpxm45SGAND
"""

# refrence: https://zhuanlan.zhihu.com/p/49479702
# analyse relationship between features, set threshold as 0.01. means visualizing the corelation stronger than 0.01
import feature_selector
features = feature_selector.FeatureSelector(data = data_lough.drop('Total',1), labels = data_lough["Total"].astype(np.float64))
features.identify_collinear(correlation_threshold = 0.01)
features.plot_collinear( plot_all = True)



# visualizaing the relationship stronger than 0.5
features.identify_collinear(correlation_threshold = 0.5)
features.plot_collinear( )
plt.xticks(rotation=45)
plt.yticks(rotation=10)


# list of collinear features to remove, visualize whcih feture can be removed
collinear_features = features.ops['collinear']
# dataframe of collinear features
features.record_collinear.head()

# visualize the importance of fatures
features.identify_zero_importance(task = 'regression', 
                            eval_metric = 'auc', 
                            n_iterations = 10, 
                             early_stopping = True)
zero_importance_features = features.ops['zero_importance']

features.plot_feature_importances(threshold = 0.99, plot_n = 18)